baseURL = "https://bitwizeshift.github.io/"
languageCode = "en-us"
title = "@bitwizeshift on software"
theme = "hugo-notepadium"
copyright = "©2021 Matthew Rodusek."

enableRobotsTXT = true
enableGitInfo = true
# TODO: enable this
# Enable Disqus
# disqusShortname = "XXX"

[author]
  name = "Matthew Rodusek"
  email = "bitwizeshift@rodusek.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "January 2, 2006"
logo = ""
# slogan = "A C++ template metaprogramming blog"
# license = "MIT"  # MIT License
repo = "https://github.com/bitwizeshift/bitwizeshift.github.io"

[params.social]
github = "bitwizeshift"
linkedin = "matthewrodusek"
email = "bitwizeshift@rodusek.com"
stackoverflow = "1678770"
twitter = "bitwizeshift"

[params.github]
username = "bitwizeshift"
repository = "bitwizeshift.github.io"

[params.comments]
enable = false  # Comments are enabled per blog post

[params.syntax]
use = "none"
theme = "github-gist"
darkTheme = "xcode-dark"

[params.nav]
showCategories = true
showTags = true

# custom navigation items

[[params.nav.custom]]
title = "About Me"
url = "/about"

[[params.nav.custom]]
title = "Tags"
url = "/tags"

[[params.nav.custom]]
title = "License"
url = "/license"
